### ISSUE TITLE
user-programs with more than 130mb when using -oformat binary

### ISSUE THREAD

**Issue by richard-hgs** [povilasb/simple-os#7]
Hi i really apreciate what you did in your OS i'm trying to compile it but the user-programs are getting this huge size when linking using -oformat binary i'm compiling it in a ubuntu linux distro. i searched in the internet and i didn't found a solution.

**Comment by povilasb** [comment]
Can't tell of the top of my head.
Will experiment later in this week.

**Comment by richard-hgs** [comment]
> Can't tell of the top of my head. Will experiment later in this week.

No worries i'm learning some things but i am rewriting my own o.s. i really appreciate your work if will close this pull since i fixed it by using a linker script! I will really invest in o.s. knowledgement here in Brazil we don't have a reference person in this kind of stuff.
